### ISSUE TITLE
Doesn't render LaTeX on existing posts

### ISSUE THREAD

**Issue by ukasiu** [marcovo/phpbb_mathjax#1]
Hi,
I want to integrate phpbb_mathjax with an existing forum, where I used [tex][/tex] for LaTeX. Now after installing phpbb_mathjax old bbcode is not rendered until I edit a post with it. How can I fix it?

**Comment by marcovo** [comment]
Hi,

I'm sorry, but I'm currently not in the ability to look into it. I did
indeed test the extension to be working for new installations, but I
haven't looked at upgrades yet, which is why the extension is not yet in
the customisation database.

One thing I thought I had concluded, is that you should remove the old
mathjax (3.0) mod, then upgrade the forum and then install the
extension. No guarantees though.

Regards,
Marco

Op 17-06-15 om 10:23 schreef Łukasz Gurdek:

**Comment by ukasiu** [comment]
I used another extension for LaTeX and I wanted to switch to phpbb_mathjax.
Thanks.

**Comment by marcovo** [comment]
Ah that changes matters. Could you provide me with a link or sth like
that to that other extension? I'm not aware of any other TeX-like extension?

Regards,
Marco

Op 17-06-15 om 12:09 schreef Łukasz Gurdek:

**Comment by sergio91pt** [comment]
@marcovo The 3.0 mod bbcode's _should_ be compatible with 3.1, as the [bbcode template](https://github.com/marcovo/phpbb_mathjax/blob/master/includes/bbcode.php#L226) wasn't even changed.

@ukasiu So, using [tex] on a new post works, but you need an edit on old posts for them to "fetch" the new bbcode definition?
The Reparse BBCode feature of the [Support Toolkit](https://www.phpbb.com/support/stk/) seems like what you need, but unfortunately 3.1 isn't supported yet.

**Comment by ukasiu** [comment]
It was an old 3.0 extension, I don't even know its name (didn't use mathjax). @sergio91pt thanks for the support toolkit tip :)

**Comment by ukasiu** [comment]
This helped a lot: https://www.phpbb.com/community/viewtopic.php?f=466&t=2273811
